package GUICRUD;

import PersistenciaCRUD.ConexionDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TiendaFormulario extends javax.swing.JFrame {
    static Connection connTienda = null;
    static Statement stTienda = null;
    static ResultSet rsTienda = null;
    public String id_modificar;
    DefaultTableModel modeloProductos;
    DefaultTableModel modeloVentas;
    /**
     * Creates new form AlumnoFormulario
     */
    public TiendaFormulario() {
        
        initComponents();
        actualizarDatos();

    }
    //Actualizar el registro
public void actualizarDatos() {
    modeloProductos = new DefaultTableModel();
    modeloVentas = new DefaultTableModel();
    llenaTablaProductos();
    llenaTablaVentas();
    this.jTable1.setModel(modeloProductos);
}//actualizarDatos

//Llenado del jTable con los Registros de la Tabla Alumno
public void llenaTablaProductos() {
    try {
        rsTienda = ConexionDB.EnlEstTienda(rsTienda, "productos");
        ResultSetMetaData rsMd = rsTienda.getMetaData();
        int cantidadColumnas = rsMd.getColumnCount();

        for (int i = 1; i <= cantidadColumnas; i++) {
            modeloProductos.addColumn(rsMd.getColumnLabel(i));
        }

        while (rsTienda.next()) {
            Object[] fila = new Object[cantidadColumnas];
            for (int i = 0; i < cantidadColumnas; i++) {
                fila[i] = rsTienda.getObject(i + 1);
            }
            modeloProductos.addRow(fila);
        }
        rsTienda.close();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}

public void llenaTablaVentas() {
    try {
        rsTienda = ConexionDB.EnlEstTienda(rsTienda, "ventas");
        ResultSetMetaData rsMd = rsTienda.getMetaData();
        int cantidadColumnas = rsMd.getColumnCount();

        for (int i = 1; i <= cantidadColumnas; i++) {
            modeloVentas.addColumn(rsMd.getColumnLabel(i));
        }

        while (rsTienda.next()) {
            Object[] fila = new Object[cantidadColumnas];
            for (int i = 0; i < cantidadColumnas; i++) {
                fila[i] = rsTienda.getObject(i + 1);
            }
            modeloVentas.addRow(fila);
        }
        rsTienda.close();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}

//Limpiar los jTextField
public void limpiarcampos(){
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
}//limpiarcampos

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Insert ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Producto");

        jButton2.setText("Mostrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Precio");

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Insertar, leer, analizar y eliminar (CRUD)");

        jLabel4.setText("Stock");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton4.setText("Modificar ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Buscar Producto");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(407, 407, 407)
                .addComponent(jButton6)
                .addContainerGap(453, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(jButton3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton1)
                                                    .addGap(2, 2, 2))
                                                .addComponent(jButton5)
                                                .addComponent(jButton4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jButton2))))))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(282, 282, 282))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(11, 11, 11)
                        .addComponent(jButton5)
                        .addGap(8, 8, 8)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //Validación
    if(jTextField1.getText().trim().isEmpty() ||
        jTextField2.getText().trim().isEmpty() ||
        jTextField3.getText().trim().isEmpty() ||
        jTextField4.getText().trim().isEmpty())
    {
        JOptionPane.showMessageDialog(null, "No se aceptan datos vacios");
        return;
    }//fin if
    //Operación con la Base de Datos
    try{
        connTienda = ConexionDB.EnlaceTienda(connTienda); 

       String sqlinsertar = "insert into productos values (?,?,?,?)";
        PreparedStatement psta = connTienda.prepareStatement(sqlinsertar);
        psta.setString(1, jTextField1.getText());
        psta.setString(2, jTextField2.getText());
        psta.setString(3, jTextField3.getText());
        psta.setString(4, jTextField4.getText());
        psta.execute();
        psta.close();
        JOptionPane.showMessageDialog(null, "Registro guardado satisfactoriamente");
        actualizarDatos();
    }catch(Exception e){
        System.out.println(e.getCause());
    }//fin try-catch

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        actualizarDatos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Validación
    if(jTextField1.getText().trim().isEmpty() ||
        jTextField2.getText().trim().isEmpty() ||
        jTextField3.getText().trim().isEmpty() ||
        jTextField4.getText().trim().isEmpty())
    {
        JOptionPane.showMessageDialog(null, "No se aceptan datos vacios");
        return;
    }//fin if

    //Operación con la Base de Datos
    try{
        connTienda = ConexionDB.EnlaceTienda(connTienda);
        String sqlactualizar = "update productos set id_producto=?,nombre=?,precio=?,stock=? where id_producto=?";
        PreparedStatement psta = connTienda.prepareStatement(sqlactualizar);
        psta.setString(1, jTextField1.getText());
        psta.setString(2, jTextField2.getText());
        psta.setString(3, jTextField3.getText());
        psta.setString(4, jTextField4.getText());
        psta.setString(5, id_modificar);
        int res = psta.executeUpdate();

        if (res > 0) {
            JOptionPane.showMessageDialog(null, "Registro modificado satisfactoriamente");
            id_modificar = jTextField1.getText();
            actualizarDatos();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo modificar el registro");
        }

        psta.close();
        limpiarcampos();
    }catch(Exception e){
        System.out.println(e.getCause());
    }//fin try-catch

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    if(jTextField1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Buscar el registro primero");
        return;
    }
    try{
        connTienda = ConexionDB.EnlaceTienda(connTienda);
        String sqleliminar = "delete from productos where id_producto=?";
        PreparedStatement psta = connTienda.prepareStatement(sqleliminar);
        psta.setString(1, id_modificar);
        int res = psta.executeUpdate();
        if(res > 0) {
            JOptionPane.showMessageDialog(null, "Registro eliminado satisfactoriamente");
            actualizarDatos();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo eliminar el registro");
        }
        psta.close();
        limpiarcampos();
    }catch(Exception e){
        e.printStackTrace();
    }
  
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

if(jTextField1.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "No se aceptan datos vacios. "
                + "Colocar solo el ID del Producto en la primer caja de texto.");
        return;
    }//fin if
    try{
        connTienda = ConexionDB.EnlaceTienda(connTienda);
        String sqlbuscar = "SELECT * FROM productos WHERE id_producto = ?";
        PreparedStatement pst = connTienda.prepareStatement(sqlbuscar);
        pst.setString(1, jTextField1.getText());
        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            jTextField1.setText(rs.getString("id_producto"));
            jTextField2.setText(rs.getString("nombre"));
            jTextField3.setText(rs.getString("precio"));
            jTextField4.setText(rs.getString("stock"));
            id_modificar = jTextField1.getText();
            JOptionPane.showMessageDialog(null, "Registro encontrado");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró el registro");
            limpiarcampos();
        }
        rs.close();
        pst.close();
    }catch(Exception e){
        System.out.println(e.getCause());
    }//fin try-catch

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
